import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding SYSTEXX by Vitrulan products...');

  const categories = [
    {
      name: 'SYSTEXX Active',
      nameEs: 'SYSTEXX Active',
      slug: 'systexx-active',
      description: 'Glass fiber wall coverings with functional benefits: magnetic, acoustic, fire protection, air purification and renovation.',
      descriptionEs: 'Revestimientos de pared de fibra de vidrio con beneficios funcionales.',
      order: 10,
      isActive: true
    },
    {
      name: 'SYSTEXX Phantasy',
      nameEs: 'SYSTEXX Phantasy',
      slug: 'systexx-phantasy',
      description: 'Glass fiber wall coverings with creative textures and opulent designs for a decorative interior.',
      descriptionEs: 'Revestimientos de fibra de vidrio con texturas creativas y diseños opulentos.',
      order: 11,
      isActive: true
    },
    {
      name: 'SYSTEXX Pure',
      nameEs: 'SYSTEXX Pure',
      slug: 'systexx-pure',
      description: 'Glass fabric wall coverings with straight lines and well-defined textures for smooth, durable surfaces.',
      descriptionEs: 'Revestimientos de tela de vidrio con líneas rectas y texturas bien definidas.',
      order: 12,
      isActive: true
    }
  ];

  const cats: Record<string, any> = {};
  for (const cat of categories) {
    const c = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat
    });
    cats[cat.slug] = c;
    console.log(`  ✅ Category: ${cat.name}`);
  }

  const products = [
    // ── ACTIVE MAGNETIC ─────────────────────────────────────────────
    {
      name: 'Active Magnetic M20',
      nameEs: 'Active Magnetic M20',
      slug: 'systexx-active-magnetic-m20',
      sku: 'SYS-ACT-MAG-M20',
      description: 'Glass fiber wall covering with magnetic surface. Smooth fleece texture. Standard magnets adhere directly to the wall. Does not create magnetic fields or interfere with Wi-Fi.',
      descriptionEs: 'Revestimiento de fibra de vidrio con superficie magnética. Los imanes estándar se adhieren directamente a la pared.',
      price: 99.99,
      images: ['/wallpapers/active-magnetic-m20.png'],
      colors: ['white', 'light-gray'],
      styles: ['functional', 'magnetic', 'commercial'],
      dimensions: 'Roll: 16 m × 95 cm | Weight: 950 g/m²',
      material: 'Glass fiber, magnetic backing (Glassfleece)',
      materialEs: 'Fibra de vidrio, respaldo magnético',
      isCustomizable: false,
      isActive: true,
      isFeatured: true,
      stock: 50,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Magnetic M22',
      nameEs: 'Active Magnetic M22',
      slug: 'systexx-active-magnetic-m22',
      sku: 'SYS-ACT-MAG-M22',
      description: 'Glass fiber wall covering with magnetic surface. Fine glass fabric texture. Available in 2.6 m, 5.2 m and 10.4 m rolls. Paintable, blends invisibly into the room.',
      descriptionEs: 'Revestimiento de fibra de vidrio con superficie magnética y textura fina.',
      price: 109.99,
      images: ['/wallpapers/active-magnetic-m22.png'],
      colors: ['white', 'light-gray'],
      styles: ['functional', 'magnetic', 'commercial'],
      dimensions: 'Roll: 2.6 m / 5.2 m / 10.4 m × 95 cm | Weight: 1,540 g/m²',
      material: 'Glass fiber, magnetic backing (glass fabric)',
      materialEs: 'Fibra de vidrio, respaldo magnético (tela de vidrio)',
      isCustomizable: false,
      isActive: true,
      isFeatured: true,
      stock: 45,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Magnetic M39',
      nameEs: 'Active Magnetic M39',
      slug: 'systexx-active-magnetic-m39',
      sku: 'SYS-ACT-MAG-M39',
      description: 'Glass fiber wall covering with magnetic surface. Woven glass fabric texture. Available in 2.6 m, 5.2 m and 10.4 m rolls. Fire rated B-s1, d0.',
      descriptionEs: 'Revestimiento de fibra de vidrio con superficie magnética y textura tejida.',
      price: 104.99,
      images: ['/wallpapers/active-magnetic-m39.png'],
      colors: ['white'],
      styles: ['functional', 'magnetic', 'commercial'],
      dimensions: 'Roll: 2.6 m / 5.2 m / 10.4 m × 95 cm | Weight: 1,470 g/m²',
      material: 'Glass fiber, magnetic backing (woven glass fabric)',
      materialEs: 'Fibra de vidrio, respaldo magnético (tela tejida)',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 40,
      categoryId: cats['systexx-active'].id
    },
    // ── ACTIVE ACOUSTHERM ────────────────────────────────────────────
    {
      name: 'Active AcousTherm 233',
      nameEs: 'Active AcousTherm 233',
      slug: 'systexx-active-acoustherm-233',
      sku: 'SYS-ACT-ACO-233',
      description: 'Glass fiber wall covering that optimizes room acoustics and saves energy. Sound absorption class E (αw 0.25). Heats rooms up to 4× faster. Only 3 mm thick.',
      descriptionEs: 'Revestimiento de fibra de vidrio que optimiza la acústica y ahorra energía.',
      price: 89.99,
      images: ['/wallpapers/active-acoustherm-233.png'],
      colors: ['white'],
      styles: ['functional', 'acoustic', 'thermal', 'commercial'],
      dimensions: 'Roll: 10.4 m / 12.0 m × 100 cm | Weight: 465 g/m²',
      material: 'Glass fiber with trapped-air acoustic core',
      materialEs: 'Fibra de vidrio con núcleo acústico de aire atrapado',
      isCustomizable: false,
      isActive: true,
      isFeatured: true,
      stock: 35,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active AcousTherm 904',
      nameEs: 'Active AcousTherm 904',
      slug: 'systexx-active-acoustherm-904',
      sku: 'SYS-ACT-ACO-904',
      description: 'Heavy-weight glass fiber wall covering with acoustic and thermal performance. Sound absorption class E. Higher density for enhanced sound control and heat retention.',
      descriptionEs: 'Revestimiento de fibra de vidrio de alta densidad con rendimiento acústico y térmico.',
      price: 94.99,
      images: ['/wallpapers/active-acoustherm-904.png'],
      colors: ['white'],
      styles: ['functional', 'acoustic', 'thermal', 'commercial'],
      dimensions: 'Roll: 10.4 m / 12.0 m × 100 cm | Weight: 600 g/m²',
      material: 'Glass fiber with trapped-air acoustic core (heavy weight)',
      materialEs: 'Fibra de vidrio con núcleo acústico de alta densidad',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 30,
      categoryId: cats['systexx-active'].id
    },
    // ── ACTIVE RENO ──────────────────────────────────────────────────
    {
      name: 'Active Reno 938',
      nameEs: 'Active Reno 938',
      slug: 'systexx-active-reno-938',
      sku: 'SYS-ACT-REN-938',
      description: 'Glass fiber textured wall covering for fast refurbishment. Special woven pattern visually compensates uneven substrates up to 2 mm. Ideal for renovation without disruption.',
      descriptionEs: 'Revestimiento de fibra de vidrio para renovación rápida. Compensa imperfecciones hasta 2 mm.',
      price: 54.99,
      images: ['/wallpapers/active-reno-938-s38-sp38.png'],
      colors: ['white', 'off-white'],
      styles: ['renovation', 'textured', 'commercial'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 210 g/m²',
      material: 'Glass fiber, woven textured pattern',
      materialEs: 'Fibra de vidrio, patrón texturizado tejido',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 60,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Reno S38',
      nameEs: 'Active Reno S38',
      slug: 'systexx-active-reno-s38',
      sku: 'SYS-ACT-REN-S38',
      description: 'Glass fiber renovation wall covering with Aqua Technology water-activated adhesive. Extremely quick to hang, minimizing downtime in high-traffic areas like hospitals.',
      descriptionEs: 'Revestimiento de renovación con tecnología Aqua de adhesivo activado por agua.',
      price: 59.99,
      images: ['/wallpapers/active-reno-938-s38-sp38.png'],
      colors: ['white', 'off-white'],
      styles: ['renovation', 'textured', 'aqua-technology', 'commercial'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 245 g/m²',
      material: 'Glass fiber, Aqua Technology (water-activated adhesive)',
      materialEs: 'Fibra de vidrio, Aqua Technology (adhesivo activado por agua)',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 55,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Reno SP38',
      nameEs: 'Active Reno SP38',
      slug: 'systexx-active-reno-sp38',
      sku: 'SYS-ACT-REN-SP38',
      description: 'Pre-pigmented glass fiber renovation wall covering with Aqua Technology. Light colors need only one coat of paint. Perfect for fast commercial renovations.',
      descriptionEs: 'Revestimiento de renovación pre-pigmentado con Aqua Technology.',
      price: 64.99,
      images: ['/wallpapers/active-reno-938-s38-sp38.png'],
      colors: ['white'],
      styles: ['renovation', 'textured', 'aqua-technology', 'pre-pigmented'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 250 g/m²',
      material: 'Glass fiber, pre-pigmented, Aqua Technology',
      materialEs: 'Fibra de vidrio, pre-pigmentada, Aqua Technology',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 50,
      categoryId: cats['systexx-active'].id
    },
    // ── ACTIVE ABSORB ────────────────────────────────────────────────
    {
      name: 'Active Absorb 604',
      nameEs: 'Active Absorb 604',
      slug: 'systexx-active-absorb-604',
      sku: 'SYS-ACT-ABS-604',
      description: 'Glass fiber wall covering with formaldehyde absorber for better indoor air quality. Permanently captures up to 65% of formaldehyde. Aqua Technology included.',
      descriptionEs: 'Revestimiento de fibra de vidrio con absorbedor de formaldehído para mejor calidad del aire.',
      price: 64.99,
      images: ['/wallpapers/active-absorb-604.png'],
      colors: ['white', 'light-gray'],
      styles: ['functional', 'air-quality', 'aqua-technology'],
      dimensions: 'Roll: 50 m × 100 cm | Weight: 195 g/m²',
      material: 'Glass fiber with formaldehyde absorber, Aqua Technology',
      materialEs: 'Fibra de vidrio con absorbedor de formaldehído',
      isCustomizable: false,
      isActive: true,
      isFeatured: true,
      stock: 40,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Absorb Glassfleece',
      nameEs: 'Active Absorb Glassfleece',
      slug: 'systexx-active-absorb-glassfleece',
      sku: 'SYS-ACT-ABS-GF',
      description: 'Smooth glass fleece wall covering with formaldehyde-absorbing properties. Perfectly smooth finish, reduces indoor air pollutants by up to 65% over its lifecycle.',
      descriptionEs: 'Revestimiento de vellón de vidrio liso con propiedades de absorción de formaldehído.',
      price: 59.99,
      images: ['/wallpapers/active-absorb-glassfleece.png'],
      colors: ['white', 'light-gray'],
      styles: ['functional', 'air-quality', 'smooth'],
      dimensions: 'Roll: 50 m × 100 cm | Weight: 125 g/m²',
      material: 'Glass fleece with formaldehyde absorber',
      materialEs: 'Vellón de vidrio con absorbedor de formaldehído',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 45,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Absorb 633',
      nameEs: 'Active Absorb 633',
      slug: 'systexx-active-absorb-633',
      sku: 'SYS-ACT-ABS-633',
      description: 'Woven glass fiber wall covering with formaldehyde absorber. Classic basket-weave texture. Aqua Technology for easy installation. Improves indoor air quality permanently.',
      descriptionEs: 'Revestimiento de fibra de vidrio tejido con absorbedor de formaldehído.',
      price: 62.99,
      images: ['/wallpapers/active-absorb-633.png'],
      colors: ['white'],
      styles: ['functional', 'air-quality', 'woven', 'aqua-technology'],
      dimensions: 'Roll: 50 m × 100 cm | Weight: 185 g/m²',
      material: 'Woven glass fiber with formaldehyde absorber, Aqua Technology',
      materialEs: 'Fibra de vidrio tejida con absorbedor de formaldehído',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 38,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Absorb 639',
      nameEs: 'Active Absorb 639',
      slug: 'systexx-active-absorb-639',
      sku: 'SYS-ACT-ABS-639',
      description: 'Fine woven glass fiber wall covering with formaldehyde-absorbing technology. Delicate texture, Aqua Technology for fast installation. Suitable for allergy sufferers.',
      descriptionEs: 'Revestimiento fino de fibra de vidrio tejida con tecnología absorbente de formaldehído.',
      price: 61.99,
      images: ['/wallpapers/active-absorb-639.png'],
      colors: ['white'],
      styles: ['functional', 'air-quality', 'woven', 'aqua-technology'],
      dimensions: 'Roll: 50 m × 100 cm | Weight: 170 g/m²',
      material: 'Fine woven glass fiber with formaldehyde absorber, Aqua Technology',
      materialEs: 'Fibra de vidrio fina tejida con absorbedor de formaldehído',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 42,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Absorb 060',
      nameEs: 'Active Absorb 060',
      slug: 'systexx-active-absorb-060',
      sku: 'SYS-ACT-ABS-060',
      description: 'Smooth glass fiber wall covering with formaldehyde absorber. Ultra-clean finish that permanently captures indoor air pollutants. Oeko-Tex certified, non-toxic.',
      descriptionEs: 'Revestimiento liso de fibra de vidrio con absorbedor de formaldehído.',
      price: 65.99,
      images: ['/wallpapers/active-absorb-060.png'],
      colors: ['white', 'light-gray'],
      styles: ['functional', 'air-quality', 'smooth'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 215 g/m²',
      material: 'Glass fiber, smooth finish, formaldehyde absorber',
      materialEs: 'Fibra de vidrio, acabado liso, absorbedor de formaldehído',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 35,
      categoryId: cats['systexx-active'].id
    },
    // ── ACTIVE FIREPROTECT ───────────────────────────────────────────
    {
      name: 'Active FireProtect FP Glassfleece',
      nameEs: 'Active FireProtect FP Glassfleece',
      slug: 'systexx-active-fireprotect-fp-glassfleece',
      sku: 'SYS-ACT-FP-GF',
      description: 'Non-combustible glass fleece wall covering. Fire rating A2-s1, d0 (non-combustible) when used with FireProtect Glue. Certified system for maximum fire protection.',
      descriptionEs: 'Revestimiento de vellón de vidrio no combustible. Clasificación de fuego A2-s1, d0.',
      price: 79.99,
      images: ['/wallpapers/active-fireprotect-fp-glassfleece.png'],
      colors: ['white', 'light-gray'],
      styles: ['fire-protection', 'smooth', 'commercial', 'hospitality'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 230 g/m²',
      material: 'Non-combustible glass fleece | Fire rating: A2-s1, d0',
      materialEs: 'Vellón de vidrio no combustible | Clasificación de fuego: A2-s1, d0',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 30,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active FireProtect FP78',
      nameEs: 'Active FireProtect FP78',
      slug: 'systexx-active-fireprotect-fp78',
      sku: 'SYS-ACT-FP-FP78',
      description: 'Heavy-weight non-flammable glass fiber wall covering for innovative fire protection. A2-s1, d0 certified system. Abrasion and impact resistant, ideal for high-traffic areas.',
      descriptionEs: 'Revestimiento de fibra de vidrio ignífugo de alta densidad para protección contra incendios.',
      price: 109.99,
      images: ['/wallpapers/active-fireprotect-fp78.png'],
      colors: ['white', 'light-gray'],
      styles: ['fire-protection', 'commercial', 'hospitality', 'healthcare'],
      dimensions: 'Roll: 15.5 m × 100 cm | Weight: 600 g/m²',
      material: 'Non-flammable glass fiber | Fire rating: A2-s1, d0',
      materialEs: 'Fibra de vidrio ignífuga | Clasificación de fuego: A2-s1, d0',
      isCustomizable: false,
      isActive: true,
      isFeatured: true,
      stock: 25,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active FireProtect FP79',
      nameEs: 'Active FireProtect FP79',
      slug: 'systexx-active-fireprotect-fp79',
      sku: 'SYS-ACT-FP-FP79',
      description: 'Non-flammable glass fiber wall covering with organic pattern. Achieves A2-s1, d0 fire rating with FireProtect Glue system. Distinctive raised diamond texture.',
      descriptionEs: 'Revestimiento de fibra de vidrio ignífugo con patrón orgánico y clasificación A2-s1, d0.',
      price: 109.99,
      images: ['/wallpapers/active-fireprotect-fp79.png'],
      colors: ['white'],
      styles: ['fire-protection', 'textured', 'commercial'],
      dimensions: 'Roll: 15.5 m × 100 cm | Weight: 600 g/m²',
      material: 'Non-flammable glass fiber, organic relief | Fire rating: A2-s1, d0',
      materialEs: 'Fibra de vidrio ignífuga, relieve orgánico | A2-s1, d0',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 25,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active FireProtect FP04',
      nameEs: 'Active FireProtect FP04',
      slug: 'systexx-active-fireprotect-fp04',
      sku: 'SYS-ACT-FP-FP04',
      description: 'Non-flammable glass fiber wall covering with vertical grid pattern. A2-s1, d0 certified system. Perfect for healthcare facilities, schools, and commercial buildings.',
      descriptionEs: 'Revestimiento de fibra de vidrio ignífugo con patrón de cuadrícula vertical.',
      price: 99.99,
      images: ['/wallpapers/active-fireprotect-fp04.png'],
      colors: ['white'],
      styles: ['fire-protection', 'textured', 'commercial', 'healthcare'],
      dimensions: 'Roll: 15.5 m × 100 cm | Weight: 500 g/m²',
      material: 'Non-flammable glass fiber | Fire rating: A2-s1, d0',
      materialEs: 'Fibra de vidrio ignífuga | Clasificación de fuego: A2-s1, d0',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 28,
      categoryId: cats['systexx-active'].id
    },
    // ── ACTIVE LOGO ──────────────────────────────────────────────────
    {
      name: 'Active Logo L65',
      nameEs: 'Active Logo L65',
      slug: 'systexx-active-logo-l65',
      sku: 'SYS-ACT-LOG-L65',
      description: 'Custom glass fabric wall covering with your company logo woven using Jacquard technique. Logo width up to 800 mm. Ideal for hotels, banks, offices and brand-conscious spaces.',
      descriptionEs: 'Revestimiento personalizado con el logo de su empresa tejido con técnica Jacquard.',
      price: 149.99,
      images: ['/wallpapers/active-logo-l65.png'],
      colors: ['white', 'custom'],
      styles: ['custom', 'branding', 'commercial', 'hospitality'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 200 g/m² | Logo width: up to 800 mm',
      material: 'Woven glass fiber, Jacquard logo technique',
      materialEs: 'Fibra de vidrio tejida, técnica Jacquard para logo',
      isCustomizable: true,
      isActive: true,
      isFeatured: true,
      stock: 20,
      categoryId: cats['systexx-active'].id
    },
    {
      name: 'Active Logo L00',
      nameEs: 'Active Logo L00',
      slug: 'systexx-active-logo-l00',
      sku: 'SYS-ACT-LOG-L00',
      description: 'Custom glass fiber wall covering with Jacquard-woven company logo. Heavier weight for premium finish. Can incorporate non-geometric shapes. Maximum logo width 800 mm.',
      descriptionEs: 'Revestimiento de fibra de vidrio personalizado con logo tejido Jacquard de mayor peso.',
      price: 159.99,
      images: ['/wallpapers/active-logo-l00.png'],
      colors: ['white', 'custom'],
      styles: ['custom', 'branding', 'commercial', 'hospitality'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 280 g/m² | Logo width: up to 800 mm',
      material: 'Heavy woven glass fiber, Jacquard logo technique',
      materialEs: 'Fibra de vidrio tejida pesada, técnica Jacquard para logo',
      isCustomizable: true,
      isActive: true,
      isFeatured: false,
      stock: 15,
      categoryId: cats['systexx-active'].id
    },
    // ── PHANTASY ─────────────────────────────────────────────────────
    {
      name: 'Phantasy Diamond Dust 072',
      nameEs: 'Phantasy Diamond Dust 072',
      slug: 'systexx-phantasy-diamond-dust-072',
      sku: 'SYS-PHA-DD-072',
      description: 'Glass fiber wall covering inspired by the spectacular structure of a diamond. Sparkling geometric relief pattern that makes every wall shine. Paintable in any NCS color.',
      descriptionEs: 'Revestimiento de fibra de vidrio inspirado en la estructura del diamante.',
      price: 79.99,
      images: ['/wallpapers/phantasy-diamond-dust-072.png'],
      colors: ['white', 'paintable'],
      styles: ['decorative', 'geometric', 'luxury'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 225 g/m²',
      material: 'Glass fiber, Jacquard woven diamond relief pattern',
      materialEs: 'Fibra de vidrio, patrón de relieve de diamante',
      isCustomizable: true,
      isActive: true,
      isFeatured: true,
      stock: 40,
      categoryId: cats['systexx-phantasy'].id
    },
    {
      name: 'Phantasy Bamboo 050',
      nameEs: 'Phantasy Bamboo 050',
      slug: 'systexx-phantasy-bamboo-050',
      sku: 'SYS-PHA-BAM-050',
      description: 'Glass fiber wall covering with a bamboo-inspired organic pattern. The unique charm of bamboo reflected in a durable woven design. Creates a natural, calming atmosphere.',
      descriptionEs: 'Revestimiento de fibra de vidrio con patrón orgánico inspirado en el bambú.',
      price: 79.99,
      images: ['/wallpapers/phantasy-bamboo-050.png'],
      colors: ['white', 'paintable'],
      styles: ['decorative', 'botanical', 'organic'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 225 g/m²',
      material: 'Glass fiber, Jacquard woven bamboo pattern',
      materialEs: 'Fibra de vidrio, patrón de bambú tejido Jacquard',
      isCustomizable: true,
      isActive: true,
      isFeatured: true,
      stock: 38,
      categoryId: cats['systexx-phantasy'].id
    },
    {
      name: 'Phantasy Versailles 080',
      nameEs: 'Phantasy Versailles 080',
      slug: 'systexx-phantasy-versailles-080',
      sku: 'SYS-PHA-VER-080',
      description: 'Glass fiber wall covering with a delicate Baroque floral chain pattern inspired by the Palace of Versailles. Adds a touch of Baroque glamour to any decor.',
      descriptionEs: 'Revestimiento de fibra de vidrio con patrón floral barroco inspirado en Versalles.',
      price: 79.99,
      images: ['/wallpapers/phantasy-versailles-080.png'],
      colors: ['white', 'paintable'],
      styles: ['decorative', 'baroque', 'classic', 'luxury'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 225 g/m²',
      material: 'Glass fiber, Jacquard woven baroque floral pattern',
      materialEs: 'Fibra de vidrio, patrón floral barroco tejido Jacquard',
      isCustomizable: true,
      isActive: true,
      isFeatured: false,
      stock: 35,
      categoryId: cats['systexx-phantasy'].id
    },
    {
      name: 'Phantasy Stardust 073',
      nameEs: 'Phantasy Stardust 073',
      slug: 'systexx-phantasy-stardust-073',
      sku: 'SYS-PHA-STA-073',
      description: 'Glass fiber wall covering with an ethereal cosmic swirl pattern inspired by the vastness of space. Flowing abstract relief adds depth and mystery to any room.',
      descriptionEs: 'Revestimiento de fibra de vidrio con patrón cósmico de remolinos inspirado en el universo.',
      price: 79.99,
      images: ['/wallpapers/phantasy-stardust-073.png'],
      colors: ['white', 'paintable'],
      styles: ['decorative', 'abstract', 'cosmic'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 225 g/m²',
      material: 'Glass fiber, Jacquard woven cosmic swirl pattern',
      materialEs: 'Fibra de vidrio, patrón cósmico tejido Jacquard',
      isCustomizable: true,
      isActive: true,
      isFeatured: false,
      stock: 32,
      categoryId: cats['systexx-phantasy'].id
    },
    // ── PURE ─────────────────────────────────────────────────────────
    {
      name: 'Pure Structure 633',
      nameEs: 'Pure Structure 633',
      slug: 'systexx-pure-structure-633',
      sku: 'SYS-PUR-STR-633',
      description: 'Classic glass fiber wall covering with a fine woven basket-weave texture. Straight lines and well-defined structure for smooth, durable surfaces. Paintable multiple times.',
      descriptionEs: 'Revestimiento clásico de fibra de vidrio con textura de cesta fina.',
      price: 49.99,
      images: ['/wallpapers/pure-structure-633.png'],
      colors: ['white'],
      styles: ['classic', 'woven', 'residential', 'commercial'],
      dimensions: 'Roll: 50 m × 100 cm | Weight: 185 g/m²',
      material: 'Woven glass fiber, basket-weave texture',
      materialEs: 'Fibra de vidrio tejida, textura de cesta',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 75,
      categoryId: cats['systexx-pure'].id
    },
    {
      name: 'Pure Jute 004',
      nameEs: 'Pure Jute 004',
      slug: 'systexx-pure-jute-004',
      sku: 'SYS-PUR-JUT-004',
      description: 'Heavy glass fiber wall covering with a bold vertical jute-inspired texture. Durable, crack-bridging, and highly abrasion resistant. Ideal for high-traffic areas.',
      descriptionEs: 'Revestimiento pesado de fibra de vidrio con textura vertical de yute.',
      price: 54.99,
      images: ['/wallpapers/pure-jute-004.png'],
      colors: ['white'],
      styles: ['textured', 'natural', 'residential', 'commercial'],
      dimensions: 'Roll: 25 m × 100 cm | Weight: 325 g/m²',
      material: 'Heavy woven glass fiber, vertical jute texture',
      materialEs: 'Fibra de vidrio pesada tejida, textura vertical de yute',
      isCustomizable: false,
      isActive: true,
      isFeatured: false,
      stock: 65,
      categoryId: cats['systexx-pure'].id
    }
  ];

  let seeded = 0;
  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product
    });
    console.log(`  ✅ ${product.name} — $${product.price}`);
    seeded++;
  }

  console.log(`\n🎉 SYSTEXX seed complete!`);
  console.log(`   Categories: ${categories.length}`);
  console.log(`   Products: ${seeded}`);
  console.log(`\n   Active: Magnetic (3) · AcousTherm (2) · Reno (3) · Absorb (5) · FireProtect (4) · Logo (2)`);
  console.log(`   Phantasy: Diamond Dust · Bamboo · Versailles · Stardust`);
  console.log(`   Pure: Structure 633 · Jute 004`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
